### PR TITLE
change Arduino Mega256 with Node MCU ESP8266 along with connections

### PR DESCRIPTION
**Pull request by samarth777**

### CODE REVIEW

**Comment by samarth777** [comment]
Can you merge my PR

**Comment by anuragrao04** [comment]
This is majorly a hardware contribution.

**Comment by anuragrao04** [comment]
This involved finding drivers, troubleshooting electronics and voltages. that deserves a point of 80

**Comment by anuragrao04** [comment]
!bounty 80

**Comment by samarth777** [comment]
I have changed earthquake-detector.ino to use Wi-Fi connectivity by sending http requests instead of Blue-Tooth

**Comment by bun137** [comment]
!bounty 180

**Comment by bun137** [comment]
giving 180, bc pr was opened here for the second issue

**Pull request closed without merging**
